### ISSUE TITLE
执行test.sh，报ImportError: Unable to import required dependencies

### ISSUE THREAD

**Issue by m199369309** [brightwang/dify-sandbox-use-check-permissions#2]
按照示例，python-requirements.txt 内容如下
pandas==2.2.3
已经成功安装
2024/12/30 14:08:09 setup.go:121: [INFO]Successfully installed numpy-2.2.1 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2024.2 six-1.17.0 tzdata-2024.2
但是执行test.sh的时候报错
Traceback (most recent call last):
File "/dependencies/code/test.py", line 29, in <module>
File "/usr/local/lib/python3.10/site-packages/pandas/__init__.py", line 19, in <module>
raise ImportError(
ImportError: Unable to import required dependencies:
numpy: Error importing numpy: you should not try to import numpy from
its source directory; please exit the numpy source tree, and relaunch
your python interpreter from there.，然后影响了后面的测试，这个需要怎么解决？

**Comment by brightwang** [comment]
换最新的 sandbox 版本在试试

**Comment by m199369309** [comment]
更换最新的版本之后，可以正常使用

**Comment by m199369309** [comment]
后续会根据官方迭代的版本持续更新代码吗？

**Comment by brightwang** [comment]
> 后续会根据官方迭代的版本持续更新代码吗？

如果有问题可以告知我，这个更新还是比较简单
